### ISSUE TITLE
Kanton Konversioskriptin virheensietökyvyn parantaminen

### ISSUE THREAD

**Issue by Vainonen** [NatLibFi/Finto-data#1051]
Konversioskripti saattaa kaatua aika pienistäkin virheistä Asterin tietueissa, jolloin päivitykset pysähtyvät siihen.

-     virheensietokykyä voisi kehittää esim. yksittäinen tietue tai kenttä voitaisiin ohittaa jos siinä on ongelma
-     tieto virheestä pitäisi saada eteenpäin
-     tietuekorjaukset pitäisi pyytää toimijakuvailulta

**Comment by osma** [comment]
Tänään tehty seuraavia:

1. Poistettu kielikoodien haku Lexvosta Finton SPARQL-rajapinnan kautta, joka usein takkuilee. Sen sijaan kielikoodit on laitettu [csv-tiedostoon](https://github.com/NatLibFi/Finto-data/blob/master/vocabularies/finaf/marc-lang-to-lexvo.csv) josta ne luetaan konversioskriptille. Poistaa yhden keskeisen ongelmatekijän kuvioista kokonaan.
2. Lisätty URIen validointitarkistuksia moneen paikkaan. Nämä eivät sinänsä aiheuttaneet kovin fataaleja ongelmia, mutta kuitenkin huonoa dataa ja ikäviä virheilmoituksia esim. Fusekin lokiin.
3. Lisätty GitHubiin näkyville [convert-warnings.log](https://github.com/NatLibFi/Finto-data/blob/master/vocabularies/finaf/convert-warnings.log) josta näkee minkälaisia virheitä on tullut konversiossa. Tarkoitus on, että tämän perusteella voidaan tehdä korjauksia Asterin tietueissin. Toimijakuvailun väki pääsee suoraan lukemaan tätä virhelistaa.

**Comment by osma** [comment]
Edelleen tekemättä:

> virheensietokykyä voisi kehittää esim. yksittäinen tietue tai kenttä voitaisiin ohittaa jos siinä on ongelma

Tämä kannattaisi tehdä niin, että yksittäisen tietueen prosessointikoodi laitetaan kokonaisuudessaan try/except-blokkiin niin, että mikä tahansa odottamaton virhe konversiosäännöissä ei kaada koko prosessia. Sen sijaan voitaisiin tulostaa WARNING ja skipata koko tietue.

**Comment by osma** [comment]
Nyt melko usein konversio hajoaa siihen, että Finton APIin tehtävä haku epäonnistuu.

Tässä esimerkki tältä päivältä (17.9.2025 aamuyön tunteina):

```
Traceback (most recent call last):
  File "/srv/Finto-data/vocabularies/finaf/convert-to-rdf.py", line 700, in <module>
    main()
  File "/srv/Finto-data/vocabularies/finaf/convert-to-rdf.py", line 466, in main
    place = get_place_uri(f['e'], f.get('0'), uri)
  File "/srv/Finto-data/vocabularies/finaf/convert-to-rdf.py", line 263, in get_place_uri
    return lookup_yso_place(place_name)
  File "/srv/Finto-data/vocabularies/finaf/convert-to-rdf.py", line 246, in lookup_yso_place
    req = requests.get(FINTO_API_BASE + 'yso-paikat/lookup', params=payload)
  File "/usr/local/virtualenvs/update-finaf/lib64/python3.9/site-packages/requests/api.py", line 73, in get
    return request("get", url, params=params, **kwargs)
  File "/usr/local/virtualenvs/update-finaf/lib64/python3.9/site-packages/requests/api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/local/virtualenvs/update-finaf/lib64/python3.9/site-packages/requests/sessions.py", line 587, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/virtualenvs/update-finaf/lib64/python3.9/site-packages/requests/sessions.py", line 701, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/virtualenvs/update-finaf/lib64/python3.9/site-packages/requests/adapters.py", line 547, in send
    raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))
```

Konversiokoodia voisi muuttaa niin, että se yrittää uudestaan jos tulee tällainen poikkeus. Tai ainakaan se ei saisi kaatua.

**Comment by osma** [comment]
Viime yönä konversio hajosi DNS-ongelmaan Finton API-kutsun yhteydessä:

```
DEBUG:root:looking up YSO place "Belmonte, Espanja"
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): api.finto.fi:443
Traceback (most recent call last):
  File "/usr/local/virtualenvs/update-finaf/lib64/python3.9/site-packages/urllib3/connection.py", line 174, in _new_conn
    conn = connection.create_connection(
  File "/usr/local/virtualenvs/update-finaf/lib64/python3.9/site-packages/urllib3/util/connection.py", line 72, in create_connection
    for res in socket.getaddrinfo(host, port, family, socket.SOCK_STREAM):
  File "/usr/lib64/python3.9/socket.py", line 966, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno -2] Name or service not known

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/virtualenvs/update-finaf/lib64/python3.9/site-packages/urllib3/connectionpool.py", line 703, in urlopen
    httplib_response = self._make_request(
  File "/usr/local/virtualenvs/update-finaf/lib64/python3.9/site-packages/urllib3/connectionpool.py", line 386, in _make_request
    self._validate_conn(conn)
  File "/usr/local/virtualenvs/update-finaf/lib64/python3.9/site-packages/urllib3/connectionpool.py", line 1042, in _validate_conn
    conn.connect()
  File "/usr/local/virtualenvs/update-finaf/lib64/python3.9/site-packages/urllib3/connection.py", line 363, in connect
    self.sock = conn = self._new_conn()
  File "/usr/local/virtualenvs/update-finaf/lib64/python3.9/site-packages/urllib3/connection.py", line 186, in _new_conn
    raise NewConnectionError(
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPSConnection object at 0x7fcd7ef981c0>: Failed to establish a new connection: [Errno -2] Name or service not known

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/virtualenvs/update-finaf/lib64/python3.9/site-packages/requests/adapters.py", line 489, in send
    resp = conn.urlopen(
  File "/usr/local/virtualenvs/update-finaf/lib64/python3.9/site-packages/urllib3/connectionpool.py", line 787, in urlopen
    retries = retries.increment(
  File "/usr/local/virtualenvs/update-finaf/lib64/python3.9/site-packages/urllib3/util/retry.py", line 592, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='api.finto.fi', port=443): Max retries exceeded with url: /rest/v1/yso-paikat/search?query=Belmonte&parent=http%3A%2F%2Fwww.yso.fi%2Fonto%2Fyso%2Fp105209&lang=fi (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fcd7ef981c0>: Failed to establish a new connection: [Errno -2] Name or service not known'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/srv/Finto-data/vocabularies/finaf/convert-to-rdf.py", line 750, in <module>
    main()
  File "/srv/Finto-data/vocabularies/finaf/convert-to-rdf.py", line 490, in main
    place = get_place_uri(f['a'], f.get('0'), uri)
  File "/srv/Finto-data/vocabularies/finaf/convert-to-rdf.py", line 297, in get_place_uri
    return lookup_yso_place(place_name)
  File "/srv/Finto-data/vocabularies/finaf/convert-to-rdf.py", line 269, in lookup_yso_place
    req = requests.get(FINTO_API_BASE + 'yso-paikat/search', params=payload)
  File "/usr/local/virtualenvs/update-finaf/lib64/python3.9/site-packages/requests/api.py", line 73, in get
    return request("get", url, params=params, **kwargs)
  File "/usr/local/virtualenvs/update-finaf/lib64/python3.9/site-packages/requests/api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/local/virtualenvs/update-finaf/lib64/python3.9/site-packages/requests/sessions.py", line 587, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/virtualenvs/update-finaf/lib64/python3.9/site-packages/requests/sessions.py", line 701, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/virtualenvs/update-finaf/lib64/python3.9/site-packages/requests/adapters.py", line 565, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='api.finto.fi', port=443): Max retries exceeded with url: /rest/v1/yso-paikat/search?query=Belmonte&parent=http%3A%2F%2Fwww.yso.fi%2Fonto%2Fyso%2Fp105209&lang=fi (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fcd7ef981c0>: Failed to establish a new connection: [Errno -2] Name or service not known'))
```

Taidanpa tehdä tähän parannuksen, että skripti ei hajoaisi kerrasta vaan yrittää uudelleen muutaman kerran ja sitten luovuttaa jos API-kutsu ei vaan onnistu.

**Comment by osma** [comment]
Nyt on muutettu skriptiä niin että se ei hajoa kerrasta jos tulee verkko-ongelmia, vaan yrittää uudelleen. Toivottavasti toimii 🤞
